#!/usr/bin/env bash

STEP=0.05  # 5% de volume

get_volume() {
    output=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    vol=$(echo "$output" | awk '{print $2}')
    muted=$(echo "$output" | grep MUTED)

    if [[ -n "$muted" ]]; then
        echo "MUTE"
        echo "MUTE"
        echo "#FF0000"
    else
        percent=$(awk "BEGIN {printf \"%.0f\", $vol * 100}")
        if (( percent > 100 )); then
            percent=100
        fi
        echo "${percent}%"
        echo "${percent}%"
    fi
}

case "$BLOCK_BUTTON" in
    3) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;  # botão direito: mute
    4) wpctl set-volume @DEFAULT_AUDIO_SINK@ $STEP+ ;; # scroll up
    5) wpctl set-volume @DEFAULT_AUDIO_SINK@ $STEP- ;; # scroll down
esac

get_volume
